dns:
  enable: true
  default-nameserver:
   - 223.5.5.5
   - 8.8.8.8
   - 119.29.29.29
  proxy-server-nameserver:
   - https://doh.pub/dns-query
   - https://dns.alidns.com/dns-query
   - tls://8.8.8.8:853
   - tls://1.1.1.1:853
  nameserver:
   - https://doh.pub/dns-query
   - https://dns.alidns.com/dns-query
  fallback:
  - 'https://dns.google/dns-query#🚀 国外线路'
  - 'https://doh.opendns.com/dns-query#🚀 国外线路'
  - 'https://cloudflare-dns.com/dns-query#🚀 国外线路'
fallback-filter:
  geoip: false
  geosite:
    - gfw
  ipcidr:
    - 240.0.0.0/4
  domain:
    - "+.google.com"
    - "+.facebook.com"
    - "+.youtube.com"
    - "+.githubusercontent.com"
    - "+.googlevideo.com"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - msftconnecttest.com
    - msftncsi.com
